#!/usr/bin/env bash
# This script audits subdomains of a given domain

function query_subdomain {
    local subdomain=$1
    local domain=$2
    local result=$(dig +short "$subdomain.$domain")
    
    if [[ -z "$result" ]]; then
        echo "No record found for $subdomain.$domain"
    else
        echo "The subdomain $subdomain is an A record and points to $result"
    fi
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
    for sub in www lb-01 web-01 web-02; do
        query_subdomain "$sub" "$domain"
    done
else
    query_subdomain "$subdomain" "$domain"
fi
