#!/usr/bin/env bash
# This script displays information about subdomains for a given domain.

# Function to get DNS record information for a subdomain
get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local result
    result=$(dig +short "${subdomain}.${domain}")
    
    if [ -n "$result" ]; then
        echo "The subdomain ${subdomain} is a A record and points to ${result}"
    else
        echo "The subdomain ${subdomain} does not have an A record"
    fi
}

# Check if the domain argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Define the domain and subdomains
domain=$1
subdomains=("www" "lb-01" "web-01" "web-02")
expected_ips=("54.237.35.158" "54.237.35.158" "3.83.253.101" "54.84.151.192")

# Check if a specific subdomain is provided
if [ -n "$2" ]; then
    get_subdomain_info "$domain" "$2"
else
    for subdomain in "${subdomains[@]}"; do
        get_subdomain_info "$domain" "$subdomain"
    done
fi
