#!/usr/bin/env bash
# Script that displays information about subdomains for a given domain
audit_subdomain() {
    local domain="$1"
    local subdomain="$2"

    if [[ -z "$subdomain" ]]; then
        subdomains=("www" "54.237.35.158" "3.83.253.101" "54.84.151.192")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig +short "$sub.$domain" | awk -v sub="$sub" \
            '{ print "The subdomain " sub " is a " $1 " record and points to " $0 }')
        echo "$result"
    done
}

if [[ "$#" -lt 1 || "$#" -gt 2 ]]; then
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

audit_subdomain "$1" "$2"
