#!/usr/bin/env bash
# Ensure Nginx is running and listening on port 80.
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo service nginx restart
