#!/usr/bin/env bash
# Ensure nginx user exists and configure Nginx to run as nginx user and listen on port 8080
id -u nginx &>/dev/null || useradd -r nginx
sed -i 's/^user .*/user nginx;/; s/# *listen 80;/listen 8080;/; s/# *listen \[::\]:80;/listen \[::\]:8080;/' /etc/nginx/nginx.conf /etc/nginx/sites-available/default
nginx -t && service nginx restart
